version: '3.8'
services:
  front:
    build:
      context: .
      dockerfile: front/Dockerfile
    container_name: vue-front-container
    ports:
      - '5173:5173'
    volumes:
      - ./front/vue_app:/app
    tty: true
  api:
    build: ./api
    container_name: go-api-container
    ports:
      - '8080:8080'
    volumes:
      - ./api:/go/src/app
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=dev
    tty: true
  db:
    image: mysql:5.7
    platform: linux/amd64
    restart: always
    volumes:
      - ./db/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dev
    ports:
      - "3400:3306"
    tty: true
  prism:
    image: stoplight/prism:4
    command: 'mock -h 0.0.0.0 /tmp/swagger.yml'
    volumes:
      - ./document/swagger.yml:/tmp/swagger.yml:ro
    ports:
      - '4010:4010'